### ISSUE TITLE
[BUG] The problem of inaccurate display of the number of unread messages

### ISSUE THREAD

**Issue by skywangch** [openimsdk/oimws#143]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

版本 commit: ea4d8b6c05e5176f104543e7519405d2801f25c9
未读消息的数目显示不正确，并且当成功发起调用请求，设置会话为已读后，消息数目不能清除，依然保持原来的数目。排查代码 openim-sdk-core/v3@v3.5.1/internal/conversation_msg/read_drawing.go: 142 发现是先获取未读消息列表，然后再清空消息计数表。但是如果未读消息列表为空的时候，就直接返回了，这时候可能计数表大于0（由于某些原因造成的不一致），除非接收到新的未读消息，否则清空计数表的代码不可到达，永远无法清零。

### Screenshots Link

相关代码：
<img width="686" alt="765e67d55aa54e8c5ff6674c24f2ec9" src="https://github.com/openimsdk/oimws/assets/28942093/dcd8c1b9-407e-48c8-8940-e17ea8881f07">

前端调用 markConversationMessageAsRead， 服务端 oimws 产生的日志：
<img width="1117" alt="0b132ca5f55b4c28e4fe9421a020a65" src="https://github.com/openimsdk/oimws/assets/28942093/986a0f0e-56a7-4ba6-a25d-5087ab9bbc71">

**Comment by skiffer-git** [comment]
This project is no longer maintained. Use 'https://www.npmjs.com/package/@openim/client-sdk' instead.
