### ISSUE TITLE
[BUG] failed to login, occur a "login repeat" error when login on the miniProgram

### ISSUE THREAD

**Issue by jamky** [openimsdk/oimws#151]
openim-im-server v3.7.1, chat 1.7.1,oimws v3.5.1-beta.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1. use the api [getToken](https://docs.openim.io/zh-Hans/restapi/apis/authenticationManagement/getToken) to get the user token(plateformID=6), and login by the jssdk method  IMSDK.login successfully 
2.  the jssdk login websocket will be killed when the weixin miniProgram goes into the background
3.  cannot pull the message by the [getAdvancedHistoryMessageList ](https://docs.openim.io/zh-Hans/sdks/api/message/getAdvancedHistoryMessageList) when the weixin miniProgram goes back into the foreground,  at this moment,you will get an error if use the IMSDK.logout method,  and you also get a "login repeat" error if you try to login again

### Screenshots Link

![image](https://github.com/user-attachments/assets/2be9580c-d091-4514-a2e3-fdba6212c295)

**Comment by Bloomingg** [comment]
You can introduce [@openim/client-sdk](https://www.npmjs.com/package/@openim/client-sdk) to directly communicate with IM Server(v3.8.2+) without the need to deploy this project.

**Comment by skiffer-git** [comment]
This project is no longer maintained. Use 'https://www.npmjs.com/package/@openim/client-sdk' instead.
