### ISSUE TITLE
Runtime error: panic: close of closed channel

### ISSUE THREAD

**Issue by yushuiying** [openimsdk/oimws#152]
### OpenIM Server Version

3.5.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

项目运行的好好的，突然报这个错， 导致 oimws 进程被杀，报错截图如下：
![Snipaste_2024-09-09_08-51-27](https://github.com/user-attachments/assets/7e7cc696-b9fc-4448-9e18-0ed18ecbaafa)

**Comment by connor-chl** [comment]
我的也是，运行一段时间后报了这个错误，后面进程就没了。之前在另一台服务器上什么错都不报，过段时间进程就会死掉，找不到问题。

panic: send on closed channel

goroutine 235573 [running]:
github.com/openimsdk/openim-sdk-core/v3/internal/interaction.(*LongConnMgr).SendReqWaitResp(0xc00393d110, {0x10dc2d8, 0xc0029f1080}, {0x10db4f0?, 0xc000f032c0}, 0x3e9, {0x10db520, 0xc000f03280})
        /root/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.1/internal/interaction/long_conn_mgr.go:145 +0x28b
github.com/openimsdk/openim-sdk-core/v3/internal/interaction.(*MsgSyncer).doConnected(0xc004e433e0, {0x10dc2d8, 0xc002dbc330})
        /root/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.1/internal/interaction/msg_sync.go:220 +0xbe
github.com/openimsdk/openim-sdk-core/v3/internal/interaction.(*MsgSyncer).handlePushMsgAndEvent(0xc002c05f28?, {{0xf8ba73, 0xb}, {0x0, 0x0}, {0x10dc2d8, 0xc002dbc330}})
        /root/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.1/internal/interaction/msg_sync.go:127 +0x39c
github.com/openimsdk/openim-sdk-core/v3/internal/interaction.(*MsgSyncer).DoListener(0xc004e433e0, {0x10dc2d8, 0xc0029f1080})
        /root/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.1/internal/interaction/msg_sync.go:105 +0x98
created by github.com/openimsdk/openim-sdk-core/v3/open_im_sdk.(*LoginMgr).run in goroutine 235527
        /root/go/pkg/mod/github.com/openimsdk/openim-sdk-core/v3@v3.5.1/open_im_sdk/userRelated.go:381 +0xa6

**Comment by skiffer-git** [comment]
This project is no longer maintained. Use 'https://www.npmjs.com/package/@openim/client-sdk' instead.
