### ISSUE TITLE
[Other]: Regarding this project, there is a plan to abandon it.

### ISSUE THREAD

**Issue by suxh** [openimsdk/oimws#153]
### What would you like to share?

看到官网中文文档，有提到这个项目计划废弃。如果是微信小程序要接入OpenIM，有其它的替代方案吗？

**Comment by Bloomingg** [comment]
If you need to use jssdk in the new version (v3.8.2+), you can introduce [@openim/client-sdk](https://www.npmjs.com/package/@openim/client-sdk) to directly communicate with IM Server without the need to deploy this project.

**Comment by skiffer-git** [comment]
This project is no longer maintained. Use 'https://www.npmjs.com/package/@openim/client-sdk' instead.
