### ISSUE TITLE
[Other]: The mage command according to the readme cannot be run.

### ISSUE THREAD

**Issue by DINLiang** [openimsdk/oimws#154]
### What would you like to share?

# 编译
mage

(.venv) bogon:oimws ding$ mage
Usage: mage [OPTIONS] COMMAND [ARGS]...
Missing command.   

(.venv) bogon:oimws ding$ mage init
Usage: mage init [OPTIONS] PROJECT_PATH

│ Missing argument 'PROJECT_PATH'. 

# 运行
mage start

**Comment by skiffer-git** [comment]
This project is no longer maintained. Use 'https://www.npmjs.com/package/@openim/client-sdk' instead.
